```python


# Linear Algebra Final Project - Finding eigenvalues and eigenvectors

In [4]:
import numpy as np
from numpy.linalg import eig, inv

# Define the matrix

In [5]:
A = np.array([[2, 3], 
              [1, 4]])


# Calculate eigenvalues and eigenvectors

In [6]:
eigenvalues, eigenvectors = eig(A)

# Diagonalize the matrix

In [7]:
D = np.diag(eigenvalues)
P = eigenvectors


# Verify A = PDP^-1

In [8]:
A_reconstructed = np.dot(P, np.dot(D, inv(P)))


# Print results

In [9]:
print("Original matrix A:\n", A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
print("\nDiagonal matrix D:\n", D)
print("\nMatrix P:\n", P)
print("\nReconstructed matrix A from PDP^-1:\n", A_reconstructed)

Original matrix A:
 [[2 3]
 [1 4]]

Eigenvalues:
 [1. 5.]

Eigenvectors:
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]

Diagonal matrix D:
 [[1. 0.]
 [0. 5.]]

Matrix P:
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]

Reconstructed matrix A from PDP^-1:
 [[2. 3.]
 [1. 4.]]


In [10]:
import numpy as np

def power_iteration(A, num_iter):
    n = A.shape[0]
    b_k = np.random.rand(n)
    
    for _ in range(num_iter):
        b_k1 = np.dot(A, b_k)
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm
    
    eigenvalue = np.dot(np.dot(b_k.T, A), b_k)
    eigenvector = b_k / np.linalg.norm(b_k)
    
    return eigenvalue, eigenvector

def calculate_eigenvalues_eigenvectors(A, num_iter=1000, tol=1e-6):
    n = A.shape[0]
    eigenvalues = []
    eigenvectors = []
    
    for i in range(n):
        B = A - np.eye(n) * A[i, i]
        
        eigenvalue, eigenvector = power_iteration(B, num_iter)
        eigenvalues.append(eigenvalue + A[i, i])
        eigenvectors.append(eigenvector)
    
    return eigenvalues, eigenvectors

# Example usage:
# Define your matrix A
A = np.array([[2, 3],
              [1, 4]])

eigenvalues, eigenvectors = calculate_eigenvalues_eigenvectors(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i, eigenvector in enumerate(eigenvectors):
    print(f"Lambda_{i+1}: {eigenvector}")


Eigenvalues: [5.0, 1.0]
Eigenvectors:
Lambda_1: [0.70710678 0.70710678]
Lambda_2: [ 0.9486833  -0.31622777]
